#ifndef _LJW_SEQLIB_EC_H_
#define _LJW_SEQLIB_EC_H_
#define SEQLIBQUEARGV 1
#define SEQLIBQUEMEM 2
#define SEQLIBQUEINIT 3
#define SEQLIBQUEFULL 4
#define SEQLIBQUEEMPTY 5
#define SEQLIBVECARGV 6
#define SEQLIBVECMEM 7
#define SEQLIBVECINIT 8
#define SEQLIBVECOBD 9
#define SEQLIBVECEMPTY 10
#define SEQLIBALGOARGV 11
#define SEQLIBALGODNF 12
#define SEQLIBALGOIVE 13
#define SEQLIBLSTARGV 14
#define SEQLIBLSTEMPTY 15
#define SEQLIBARRARGV 16
#define SEQLIBARROBD 17
#endif
